#+ endpoint: https://api.data.netwerkdigitaalerfgoed.nl/datasets/hackalod/GVN/services/GVN/sparql
#+ summary:  Find all results matching a certain year, in this case 1893

PREFIX dct: <http://purl.org/dc/terms/>

SELECT * WHERE {
  ?sub dct:created "1893" .
} LIMIT 1000